### ISSUE TITLE
Use APIs instead of scraping /pulse

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#122]
Use the Statistics APIs (https://developer.github.com/v3/repos/statistics/) instead of scraping `/:user/:repo/pulse`.

All of the information is there, I've just been too impatient to actually put it together, so I scraped the page instead.

**Comment by duckinator** [comment]
information needed:

1. [ ] number of authors
2. [ ] number of commits
3. [ ] number of files changed
4. [ ] additions
5. [ ] deletions

**Comment by duckinator** [comment]
As a fallback in case the API can't provide the information in a useful way:

https://github.com/rubygems/rubygems/compare/master@%7B2017-06-01%7D...master@%7B2017-07-01%7D has equivalent information to `/:user/:repo/pulse`, but it's more tedious to extract.

HOWEVER, it lets you specify the date range, which is super important and means we can generate reports for _any date period_ if we use it.

**Comment by duckinator** [comment]
need this for https://github.com/rubytogether/rubytogether.org/pull/91/files

**Comment by duckinator** [comment]
hacky garbage partial thing from messing with the API:

```ruby
#!/usr/bin/env ruby

require 'open-uri'
require 'json'
require 'pp'

def format_weeks(weeks_array)
  weeks_array.map { |weeks|
    weeks = weeks.dup

    timestamp = weeks.delete('w')

    date = Date.strptime(timestamp.to_s, '%s')

    [date, weeks]
  }.to_h
end

def simplify_statistics(stats_array)
  stats_array.map { |stats|
    [stats['author']['login'], format_weeks(stats['weeks'])]
  }.to_h
end

json = open('https://api.github.com/repos/rubygems/rubygems/stats/contributors').read
contributors = simplify_statistics(JSON.parse(json))

end_date = Date.new(2017, 07, 01)

# TODO: find contributions for the month prior to `end_date`.

pp contributors
```

**Comment by duckinator** [comment]
The `Contributions` class should provide all of the information for this. Need to add better tests and actually use it.

TODO:

1. [ ] Verify `Contributions` class provides all of the [required information](https://github.com/how-is/how_is/issues/122#issuecomment-312462725).
2. [ ] Verify the output of `Contributions#summary` includes all of the information we want.
3. [ ] Add more tests for `Contributions` class &mdash; see below.
3. [ ] Switch from using `Pulse` to using `Contributions`.
4. [ ] Remove `Pulse` class.

---

Methods that need tests on the `Contributions` class:

* [ ] `#commits`
* [ ] `#changes`
* [ ] `#changed_files`
* [ ] `#compare_url`
* [ ] `#additions_count`
* [ ] `#deletions_count`
* [ ] `#pretty_start_date`
* [ ] `#pretty_end_date`
* [ ] `#summary`

**Comment by duckinator** [comment]
Closed by #212.
